### ISSUE TITLE
import texthero error

### ISSUE THREAD

**Issue by s18392130805** [jbesomi/texthero#122] opened 2020-07-26 12:46 UTC
[nltk_data] Error loading stopwords: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
⚠ Skipping model package dependencies and setting `--no-deps`. You don't seem to
have the spaCy package itself installed (maybe because you've built from
source?), so installing the model dependencies would cause spaCy to be
downloaded, which probably isn't what you want. If the model package has other
dependencies, you'll have to install them manually.
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\texthero\stopwords.py", line 14, in <module>
    spacy_model = spacy.load("en_core_web_sm")
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\ProgramFiles\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\ProgramFiles\Anaconda3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

**Comment by mk2510** [comment] 2020-07-26 17:42
Hi,

as far, as I can read from your error message you are missing the spacy package in your python. If you install spacy in your anaconda you will probably resolve this issue. 
Just let me know if it works for you?

**Comment by s18392130805** [comment] 2020-07-27 01:32
Thank you very much for your reply. I have installed the spacy package in my anaconda and the version is 2.3.2, but there still has the issue.

**Comment by s18392130805** [comment] 2020-07-27 01:33
> Hi,
> 
> as far, as I can read from your error message you are missing the spacy package in your python. If you install spacy in your anaconda you will probably resolve this issue.
> Just let me know if it works for you!
> 
> Cheers!
Thank you very much for your reply. I have installed the spacy package in my anaconda and the version is 2.3.2, but there still has the issue.

**Comment by s18392130805** [comment] 2020-07-27 01:34
> Hi,
> 
> as far, as I can read from your error message you are missing the spacy package in your python. If you install spacy in your anaconda you will probably resolve this issue.
> Just let me know if it works for you!
> 
> Cheers!

**Comment by s18392130805** [comment] 2020-07-27 03:48
I fixed the issue by downloading the en_core_web_sm manually!

**Comment by mk2510** [comment] 2020-07-27 08:53
I found [this](https://github.com/explosion/spaCy/issues/3226) issue on the web when you are using anaconda as an environment. If I understood it right, the problem is, that spacy will normally install it outside the anaconda env to the standard python distribution. Then you have to force anaconda to install it inside

**Comment by jbesomi** [comment] 2020-07-27 13:21
@mk2510, in future, we might consider having a "Troubleshooting" or a "FAQ" page on the website that addresses and explain these kinds of issues.

**Comment by jbesomi** [comment] 2020-07-27 13:24
I'm closing this as it has been solved.

**If it happens to you to have the same issue:**

```
python -m spacy download en_core_web_sm
```

This will install `en_core_web_sm`

**Closed by jbesomi** 2020-07-27 13:24 UTC
